name: CICD
on:
  push:
    branches:
      - main
jobs:
  release:
    uses: cloud-cli/workflows/.github/workflows/npm-build-release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [release]
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: cloud-cli/d0