name: Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: cloud-cli/d0
      buildCommand: "npm i -g pnpm@10 && pnpm i && pnpm build"